### ISSUE TITLE
Unable to find split_file.R

### ISSUE THREAD

**Issue by hiraksarkar** [comprna/SUPPA_supplementary_data#1]
To run the experiments, and specifically run this following command 
`~/scripts/split_file.R ~/tra2/Salmon/quantification/iso_tpm.txt SRR1513329,SRR1513330,SRR1513331 SRR1513332,SRR1513333,SRR1513334 ~/tra2/Salmon/quantification/CTRL.tpm ~/tra2/Salmon/quantification/KD.tpm `
 the scripts folder is required which is currently not present in the https://github.com/comprna/SUPPA repo. 

so the script fails with the following error, 
`./scripts/split_file.R: No such file or directory`

**Comment by JLTrincado** [comment]
Hi!
I have included this file in [https://github.com/comprna/SUPPA](url) repo, as /scripts/split_file.R
Thanks for your comment

**Comment by hiraksarkar** [comment]
Thanks @JLTrincado .. Can you please take a look at the issue of fasta file !!
